/* CSP Screener frontend — MVP.
   Loads data/results.json (generated by screen.py), ranks best contract
   per ticker, renders a sortable/filterable leaderboard. */
(function () {
  "use strict";

  const COLS = [
    { key: "__rank", label: "#", num: false },
    { key: "ticker", label: "标的", num: false },
    { key: "expiration", label: "到期日", num: false, fmt: v => v.slice(5) },
    { key: "dte", label: "DTE", num: true },
    { key: "strike", label: "Strike", num: true, fmt: v => "$" + v.toFixed(0) },
    { key: "spot", label: "现价", num: true, fmt: v => "$" + v.toFixed(2) },
    { key: "mid", label: "权利金", num: true, fmt: v => v.toFixed(2) },
    { key: "breakeven", label: "盈亏平衡", num: true, fmt: v => "$" + v.toFixed(2) },
    { key: "ann_yield", label: "年化%", num: true, cls: "anny", fmt: v => v.toFixed(1) + "%" },
    { key: "buffer", label: "Buffer%", num: true, fmt: v => v.toFixed(1) + "%" },
    { key: "delta", label: "Delta", num: true, fmt: v => v.toFixed(2) },
    { key: "oi", label: "OI", num: true, fmt: v => v.toLocaleString() },
    { key: "score", label: "分数", num: true, score: true },
  ];

  let all = [];        // best-per-ticker rows
  let view = [];
  let sortKey = "score", sortDir = -1;
  let expanded = null;

  const $ = id => document.getElementById(id);

  function bestPerTicker(rows) {
    const m = new Map();
    for (const r of rows) {
      const cur = m.get(r.ticker);
      if (!cur || r.score > cur.score) m.set(r.ticker, r);
    }
    return [...m.values()];
  }

  function applyFilters() {
    const q = $("search").value.trim().toUpperCase();
    const minS = parseFloat($("minScore").value) || 0;
    view = all.filter(r =>
      (!q || r.ticker.includes(q)) && r.score >= minS);
    view.sort((a, b) => {
      const va = a[sortKey], vb = b[sortKey];
      const c = (typeof va === "string") ? va.localeCompare(vb) : va - vb;
      return c * sortDir;
    });
    render();
  }

  function render() {
    // header
    $("headrow").innerHTML = COLS.map(c => {
      const arrow = c.key === sortKey ? (sortDir === -1 ? " ▼" : " ▲") : "";
      return `<th data-key="${c.key}">${c.label}<span class="arrow">${arrow}</span></th>`;
    }).join("");
    document.querySelectorAll("#headrow th").forEach(th => {
      th.onclick = () => {
        const k = th.dataset.key;
        if (k === sortKey) sortDir *= -1;
        else { sortKey = k; sortDir = -1; }
        applyFilters();
      };
    });

    // body
    const html = [];
    view.forEach((r, i) => {
      const tds = COLS.map(c => {
        if (c.key === "__rank") return `<td class="rank">${i + 1}</td>`;
        if (c.key === "ticker") return `<td class="ticker">${r.ticker}</td>`;
        let v = c.fmt ? c.fmt(r[c.key]) : r[c.key];
        if (c.score) {
          return `<td class="scorecell"><span class="scoreval">${r.score.toFixed(1)}</span>` +
            `<div class="scorebar"><i style="width:${Math.min(100, r.score)}%"></i></div></td>`;
        }
        const cls = c.cls ? ` class="${c.cls}"` : "";
        return `<td${cls}>${v}</td>`;
      }).join("");
      html.push(`<tr class="mainrow" data-t="${r.ticker}">${tds}</tr>`);
      if (expanded === r.ticker) html.push(detailRow(r));
    });
    $("body").innerHTML = html.join("") || `<tr><td colspan="${COLS.length}" style="text-align:center;color:#999;padding:30px">没有符合条件的结果</td></tr>`;
    document.querySelectorAll("tr.mainrow").forEach(tr => {
      tr.onclick = () => {
        expanded = (expanded === tr.dataset.t) ? null : tr.dataset.t;
        render();
      };
    });
    $("count").textContent = `共 ${view.length} 个标的`;
  }

  function kv(k, v) {
    return `<div><span class="k">${k}</span><span class="v">${v}</span></div>`;
  }

  function detailRow(r) {
    return `<tr class="detail"><td colspan="${COLS.length}"><div class="detail-grid">` +
      kv("Bid / Ask", `${r.bid.toFixed(2)} / ${r.ask.toFixed(2)}`) +
      kv("IV", (r.iv != null ? r.iv.toFixed(1) + "%" : "—")) +
      kv("Volume", (r.volume || 0).toLocaleString()) +
      kv("股票分", `${r.stock_score.toFixed(1)}（质量 ${r.quality.toFixed(0)} / 趋势 ${r.trend.toFixed(0)} / VRP ${r.vrp.toFixed(1)}）`) +
      kv("合约适配分", r.contract_fit.toFixed(1)) +
      kv("财报", (r.earnings || "—") + (r.earn_gate < 1 ? `（×${r.earn_gate}）` : "")) +
      `</div></td></tr>`;
  }

  fetch("data/results.json")
    .then(r => { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
    .then(d => {
      all = bestPerTicker(d.rows || []);
      const nTickers = new Set((d.rows || []).map(r => r.ticker)).size;
      $("meta").innerHTML =
        `数据日期 <b>${d.as_of || "—"}</b><br>覆盖 <b>${nTickers}</b> 个标的 · <b>${(d.rows || []).length}</b> 个合格合约`;
      applyFilters();
    })
    .catch(e => {
      $("meta").textContent = "数据加载失败：" + e.message;
    });

  $("search").addEventListener("input", applyFilters);
  $("minScore").addEventListener("input", () => {
    $("minScoreVal").textContent = $("minScore").value;
    applyFilters();
  });
})();
